name: Build-APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Rozbalíme přiložený archiv se zdrojovým kódem
    - name: Unzip project
      run: unzip PivnicekSimple.zip

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - # 1) rychlá instalace Gradlu do běžícího runneru
- name: Install Gradle
  run: |
    sudo apt-get update -y
    sudo apt-get install -y gradle

# 2) sestavení APK pomocí „gradle …“
- name: Build debug APK
  run:
    cd pivnicek_simple/android
    gradle assembleDebug            # ⬅️  už nevoláme ./gradlew

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Pivnicek-debug.apk
        path: pivnicek_simple/android/app/build/outputs/apk/debug/app-debug.apk
