name: Build-APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Rozbalíme přiložený archiv se zdrojovým kódem
    - name: Unzip project
      run: unzip PivnicekSimple.zip

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

         # nainstalujeme Android SDK + licence
    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 34
        ndk: false

    # nainstalujeme Gradle 8.4
    - name: Set up Gradle 8.4
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.4

    # sestavíme debug APK
    - name: Build debug APK
      run: |
        cd pivnicek_simple/android
        gradle assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Pivnicek-debug.apk
        path: pivnicek_simple/android/app/build/outputs/apk/debug/app-debug.apk
