name: Build-APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1 – checkout
    - uses: actions/checkout@v4

    # 2 – rozbalit zdroják
    - name: Unzip project
      run: unzip PivnicekSimple.zip

    # 3 – ikonka → systémová
    - name: Patch manifest icon
      run: |
        find . -name AndroidManifest.xml -exec \
          sed -i 's|@mipmap/ic_launcher|@android:drawable/ic_menu_info_details|g' {} +

    # 4 – Compose compiler 1.5.12
    - name: Set compose compiler 1.5.12
      run: |
        sed -i 's|kotlinCompilerExtensionVersion.*|kotlinCompilerExtensionVersion "1.5.12"|' \
          pivnicek_simple/android/app/build.gradle

    # 5 – Java 17 i pro Javac
    - name: Force Java 17 compileOptions
      run: |
        APP_GRADLE="pivnicek_simple/android/app/build.gradle"
        # vlož compileOptions dovnitř bloku android { ... } (pokud tam už není)
        grep -q 'compileOptions' "$APP_GRADLE" || \
          sed -i '/^android {/a\    compileOptions {\n        sourceCompatibility JavaVersion.VERSION_17\n        targetCompatibility JavaVersion.VERSION_17\n    }' "$APP_GRADLE"

    # 6 – JDK 17
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'

    # 7 – Android SDK
    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 34
        ndk: false

    # 8 – Gradle 8.6
    - uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.6

    # 9 – build
    - name: Build debug APK
      run: |
        cd pivnicek_simple/android
        gradle assembleDebug

    # 10 – artefakt
    - uses: actions/upload-artifact@v4
      with:
        name: Pivnicek-debug.apk
        path: pivnicek_simple/android/app/build/outputs/apk/debug/app-debug.apk
